server:
  port: 8080
spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      # Kafka服务器
      bootstrap-servers: 10.112.184.214:9092
      auto-offset-reset: latest
      enable-auto-commit: false
      ack-mode: MANUAL
  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: 1261821731@qq.com
    password: ywlcbmxrjdtwhgaf
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    username:
    password:
    url: jdbc:clickhouse://10.112.196.200:8123/default
mail:
  username: ysuchenjiaxuan@163.com #邮箱发送账号
  password: VMMAKYRRYAHBZAQU  #邮箱授权码
  host: smtp.163.com
  port: 465
  auth: true
  tls: true
  from: ysuchenjiaxuan@163.com
  to: ysuchenjiaxuan@163.com